name: Deploy to Amazon ECS

on:
  push:
    branches:
      - master

env:
  PROJECT_NAME: github-test
  APP_NAME: github-test

defaults:
  run:
    shell: bash

jobs:
  build-deploy:
    name: Build
    runs-on: ubuntu-latest
    steps:
      ### < Mapping Branch to the Environment
      - name: Set env vars (master)
        if: endsWith(github.ref, '/master')
        run: |
          echo "ENV_NAME=master" >> $GITHUB_ENV
          echo "SECRET_WITH_ASTERISK=${{ secrets.SECRET_WITH_ASTERISK }}" >> $GITHUB_ENV
          echo "SECRET_WITHOUT_ASTERISK=${{ secrets.SECRET_WITHOUT_ASTERISK }}" >> $GITHUB_ENV
          echo "THIRD_SECRET=${{ secrets.THIRD_SECRET }}" >> $GITHUB_ENV
          echo "FOURTH_ONE=${{ secrets.MASTER_FOURTH_ONE }}" >> $GITHUB_ENV
          echo "SECRET_IN_ENVIRONMENT=${{ secrets.SECRET_IN_ENVIRONMENT }}" >> $GITHUB_ENV

      - name: Set env vars (dev)
        if: endsWith(github.ref, '/dev')
        run: |
          echo "ENV_NAME=dev" >> $GITHUB_ENV
          echo "SECRET_WITH_ASTERISK=${{ secrets.DEV_SECRET_WITH_ASTERISK }}" >> $GITHUB_ENV
          echo "SECRET_WITHOUT_ASTERISK=${{ secrets.DEV_SECRET_WITHOUT_ASTERISK }}" >> $GITHUB_ENV
          echo "THIRD_SECRET=${{ secrets.DEV_THIRD_SECRET }}" >> $GITHUB_ENV
          echo "FOURTH_ONE=${{ secrets.DEV_FOURTH_ONE }}" >> $GITHUB_ENV

      - name: Next step with adding more env vars
        run: |
          echo "COMPOSITE_ENV_VAR=${{ env.PROJECT_NAME }}-${{ env.ENV_NAME }}" >> $GITHUB_ENV
          echo "SOME_OTHER_VAR=look_at_me" >> $GITHUB_ENV

      - name: Last step so far
        run: |
          echo "Hello from pipeline"
